# Generated by Django 2.2.7 on 2019-11-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191120_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='berat',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
