# Generated by Django 2.2.7 on 2019-11-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_berat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='berat',
        ),
    ]
